//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirst
{
    using System;
    
    public partial class GetCoursesResult
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public short FullPrice { get; set; }
    }
}
